name: "Run Aca-Py Integration Tests"
description: "Run integration tests for Aca-Py"
author: "iancostanzo@gmail.com"
inputs:
  TEST_SCOPE:
    description: "Set of flags that defines the test scope"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: run-integration-tests-acapy
      run: ./run_bdd ${{ inputs.TEST_SCOPE }}
      shell: bash
      env:
        NO_TTY: "1"
      working-directory: acapy/demo
branding:
  icon: "mic"
  color: "purple"
